# Generated by Django 2.1.3 on 2018-12-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonfile',
            name='evaluated',
            field=models.BooleanField(default='False'),
        ),
    ]
