# Generated by Django 2.1.3 on 2018-12-17 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181217_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(null=True, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
