# Generated by Django 2.1.3 on 2018-12-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lessonfile_evaluated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclassassociation',
            name='subject_class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderador', to='home.SubjectClass'),
        ),
    ]
