# Generated by Django 2.1.3 on 2018-11-27 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181127_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subject_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.SubjectClass'),
        ),
    ]
