# Generated by Django 2.1.3 on 2018-12-17 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181217_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationofsubjects',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='moderador', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
