# Generated by Django 2.1.3 on 2018-11-28 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subject_class',
        ),
        migrations.AddField(
            model_name='subjectclass',
            name='users',
            field=models.ManyToManyField(related_name='subjectclasses', to=settings.AUTH_USER_MODEL),
        ),
    ]
