# Generated by Django 2.1.3 on 2018-11-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181122_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonfile',
            name='reviewer',
        ),
    ]
