# Generated by Django 2.1.3 on 2018-11-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181128_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='home.SubjectClass'),
        ),
    ]
