# Generated by Django 2.1.3 on 2018-12-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181217_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
